version: '3.8'
services:
  postgres:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_USER: tdtt_user
      POSTGRES_PASSWORD: tdtt_password
      POSTGRES_DB: tdtt_db
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
